import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <nav style={{background: "#E4E3D3" , width:"100%" ,
        height:"90px" ,
        fontSize:"15px" ,
        color:"#2E2D4D" ,
        display:"flex",
        justifyContent:"flex-end",
        padding:"1em",
        alignItems:"center"

        }}>
          <div
          style={{
            height: "2px",
            backgroundColor: "#ccc",
            width: "100%",
            margin: "0",
          }}
        ></div>
          <Link style ={{margin: "10px", color: "#6B705C" }}  href="/">Home </Link>
          <Link style ={{margin: "10px" , color: "#6B705C"}}  href="/posts">Posts </Link>
          <Link style ={{margin: "10px"  , color: "#6B705C"}}  href="/artical">Artical </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
